### ISSUE TITLE
Feature 1: User can view list of coins with prices

### ISSUE THREAD

**Issue by Sean-Hughes-1** [Sean-Hughes-1/ajax-project-crypto#1]
## ⚙️ Feature

> ##### Users will be able to view the first 100 coins in our list with the latest live price in USD

## 📐 Functionality

> ##### Upon page load the DOM will be built to display the first 100 coins in a table with the following columns: Coin, Price, Action. Each Row will Contain the coin image, the coin name, coin's 3 character abbreviation in the coin column. The price column will display the latest price of that coin in USD. The action column will not be used yet in this feature.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/Sean-Hughes-1/ajax-project-crypto/assets/53235890/944ebdd2-b09c-4af2-8173-f845844554cf)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Build HTML and CSS using dummy data.
- [ ] Javascript: Create function that renders a table row. 
- [ ] Javascript: Create a function that puts the rendered row on the DOM
- [ ] Javascript: Create a function to get the list of coins with photo assets, etc. and save to local storage
- [ ] Javascript: Create a function that gets pricing info and combines the list/assets into an object with the price information
- [ ] Pass the list object through the render row function to test if it is making the row correctly
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
